import type {
  ChatListQuery,
  FinanceJournalQuery,
  GroupListQuery,
  LessonListQuery,
  PaymentListQuery,
  StudentListQuery,
  TariffListQuery,
  TrialOccurrenceQuery,
  WeeklyScheduleQuery,
} from '@arava/shared';

export const queryKeys = {
  activity: ['activity'] as const,
  attention: (filters: object = {}) => ['attention', 'list', filters] as const,
  attentionSummary: (userId?: string) => ['attention', 'summary', userId] as const,
  backups: ['backups', 'list'] as const,
  backupStatus: ['backups', 'status'] as const,
  chats: (accessKey: string, query: ChatListQuery) => ['chats', accessKey, 'list', query] as const,
  chatMessages: (accessKey: string, conversationId: string) =>
    ['chats', accessKey, 'messages', conversationId] as const,
  studentCommunication: (accessKey: string, studentId: string) =>
    ['student-communication', accessKey, studentId] as const,
  branches: (includeArchived = false) => ['branches', { includeArchived }] as const,
  dashboard: ['dashboard', 'stats'] as const,
  group: (id: string) => ['groups', 'detail', id] as const,
  groupRoster: (id: string, date: string, accessKey: string) =>
    ['groups', 'roster', id, date, accessKey] as const,
  groups: (query: GroupListQuery) => ['groups', 'list', query] as const,
  integrationLog: ['integration', 'log'] as const,
  integrationConflicts: ['integration', 'conflicts'] as const,
  integrationReconciliation: ['integration', 'reconciliation'] as const,
  integrationPreview: ['integration', 'initial-preview'] as const,
  integrationStatus: ['integration', 'status'] as const,
  lead: (id: string, accessKey: string) => ['leads', accessKey, 'detail', id] as const,
  leads: (accessKey: string, query: object = {}) => ['leads', accessKey, 'list', query] as const,
  trials: (accessKey: string, query: object = {}) => ['trials', accessKey, query] as const,
  trialOccurrences: (accessKey: string, query: TrialOccurrenceQuery) =>
    ['trial-occurrences', accessKey, query] as const,
  webActions: (userId?: string) => ['web-actions', userId] as const,
  attendance: (lessonId: string) => ['attendance', lessonId] as const,
  attendanceToday: (date: string) => ['attendance', 'today', date] as const,
  lesson: (id: string) => ['lessons', 'detail', id] as const,
  lessons: (query: LessonListQuery) => ['lessons', 'list', query] as const,
  financeStats: (branchId?: string) => ['finance', 'stats', { branchId }] as const,
  financeJournal: (query: FinanceJournalQuery) => ['finance', 'journal', query] as const,
  financeToday: (date: string, branchId?: string) =>
    ['finance', 'today', { branchId, date }] as const,
  payments: (query: PaymentListQuery) => ['payments', 'list', query] as const,
  schedules: (query: WeeklyScheduleQuery) => ['schedules', 'list', query] as const,
  setting: (key: string) => ['settings', key] as const,
  student: (id: string) => ['students', 'detail', id] as const,
  studentFinance: (id: string) => ['students', 'finance', id] as const,
  students: (query: StudentListQuery) => ['students', 'list', query] as const,
  system: ['system', 'information'] as const,
  updates: (userId?: string) => ['system', 'updates', userId] as const,
  tariff: (id: string) => ['tariffs', 'detail', id] as const,
  tariffs: (query: TariffListQuery) => ['tariffs', 'list', query] as const,
  staffOptions: ['users', 'staff-options'] as const,
  users: ['users'] as const,
  trainerProfile: (id: string, month: string, accessKey: string) =>
    ['trainers', 'profile', id, month, accessKey] as const,
};
