export interface RuntimeMigration {
  id: string;
  statements: readonly string[];
}

export const runtimeMigrations: readonly RuntimeMigration[] = [
  {
    id: '20260803000000_initial',
    statements: [
      `CREATE TABLE "Contact" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "firstName" TEXT NOT NULL,
        "lastName" TEXT NOT NULL,
        "email" TEXT,
        "phone" TEXT,
        "status" TEXT NOT NULL DEFAULT 'lead',
        "companyId" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "Contact_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE SET NULL ON UPDATE CASCADE
      )`,
      `CREATE TABLE "Company" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "name" TEXT NOT NULL,
        "website" TEXT,
        "industry" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL
      )`,
      `CREATE TABLE "Opportunity" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "title" TEXT NOT NULL,
        "value" INTEGER NOT NULL DEFAULT 0,
        "stage" TEXT NOT NULL DEFAULT 'lead',
        "companyId" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "Opportunity_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE SET NULL ON UPDATE CASCADE
      )`,
      `CREATE TABLE "ActivityEvent" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "title" TEXT NOT NULL,
        "detail" TEXT NOT NULL,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      `CREATE TABLE "AppSetting" (
        "key" TEXT NOT NULL PRIMARY KEY,
        "value" TEXT NOT NULL,
        "updatedAt" DATETIME NOT NULL
      )`,
      'CREATE UNIQUE INDEX "Contact_email_key" ON "Contact"("email")',
      'CREATE INDEX "Contact_companyId_idx" ON "Contact"("companyId")',
      'CREATE INDEX "Contact_status_idx" ON "Contact"("status")',
      'CREATE INDEX "Company_name_idx" ON "Company"("name")',
      'CREATE INDEX "Opportunity_companyId_idx" ON "Opportunity"("companyId")',
      'CREATE INDEX "Opportunity_stage_idx" ON "Opportunity"("stage")',
      'CREATE INDEX "ActivityEvent_createdAt_idx" ON "ActivityEvent"("createdAt")',
    ],
  },
  {
    id: '20260804000000_sprint_1',
    statements: [
      `CREATE TABLE "User" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "email" TEXT NOT NULL,
        "fullName" TEXT NOT NULL,
        "passwordHash" TEXT NOT NULL,
        "role" TEXT NOT NULL,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "mustChangePassword" BOOLEAN NOT NULL DEFAULT false,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL
      )`,
      `CREATE TABLE "Session" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "tokenHash" TEXT NOT NULL,
        "userId" TEXT NOT NULL,
        "expiresAt" DATETIME NOT NULL,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "lastUsedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      `CREATE TABLE "Branch" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "name" TEXT NOT NULL,
        "address" TEXT NOT NULL,
        "phone" TEXT NOT NULL,
        "description" TEXT,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL
      )`,
      `CREATE TABLE "UserBranch" (
        "userId" TEXT NOT NULL,
        "branchId" TEXT NOT NULL,
        CONSTRAINT "UserBranch_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT "UserBranch_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
        PRIMARY KEY ("userId", "branchId")
      )`,
      `CREATE TABLE "Student" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "firstName" TEXT NOT NULL,
        "lastName" TEXT NOT NULL,
        "middleName" TEXT,
        "birthDate" DATETIME,
        "gender" TEXT,
        "phone" TEXT,
        "email" TEXT,
        "status" TEXT NOT NULL DEFAULT 'ACTIVE',
        "branchId" TEXT NOT NULL,
        "notes" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL,
        "archivedAt" DATETIME,
        CONSTRAINT "Student_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "StudentContact" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "studentId" TEXT NOT NULL,
        "fullName" TEXT NOT NULL,
        "relationship" TEXT NOT NULL,
        "phone" TEXT NOT NULL,
        "secondaryPhone" TEXT,
        "email" TEXT,
        "telegram" TEXT,
        "whatsapp" BOOLEAN NOT NULL DEFAULT false,
        "isPrimary" BOOLEAN NOT NULL DEFAULT false,
        "notes" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "StudentContact_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      'CREATE UNIQUE INDEX "User_email_key" ON "User"("email")',
      'CREATE INDEX "User_role_isActive_idx" ON "User"("role", "isActive")',
      'CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash")',
      'CREATE INDEX "Session_userId_idx" ON "Session"("userId")',
      'CREATE INDEX "Session_expiresAt_idx" ON "Session"("expiresAt")',
      'CREATE INDEX "Branch_name_idx" ON "Branch"("name")',
      'CREATE INDEX "Branch_isActive_idx" ON "Branch"("isActive")',
      'CREATE INDEX "UserBranch_branchId_idx" ON "UserBranch"("branchId")',
      'CREATE INDEX "Student_branchId_status_idx" ON "Student"("branchId", "status")',
      'CREATE INDEX "Student_lastName_firstName_idx" ON "Student"("lastName", "firstName")',
      'CREATE INDEX "Student_phone_idx" ON "Student"("phone")',
      'CREATE INDEX "Student_archivedAt_idx" ON "Student"("archivedAt")',
      'CREATE INDEX "StudentContact_studentId_idx" ON "StudentContact"("studentId")',
      'CREATE INDEX "StudentContact_studentId_isPrimary_idx" ON "StudentContact"("studentId", "isPrimary")',
      'CREATE INDEX "StudentContact_phone_idx" ON "StudentContact"("phone")',
      'CREATE UNIQUE INDEX "StudentContact_one_primary_key" ON "StudentContact"("studentId") WHERE "isPrimary" = true',
    ],
  },
  {
    id: '20260805000000_sprint_2',
    statements: [
      `CREATE TABLE "DanceGroup" (
        "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "branchId" TEXT NOT NULL,
        "direction" TEXT NOT NULL, "ageFrom" INTEGER, "ageTo" INTEGER, "coachId" TEXT,
        "assistantCoachId" TEXT, "capacity" INTEGER NOT NULL DEFAULT 20,
        "status" TEXT NOT NULL DEFAULT 'RECRUITING', "description" TEXT, "color" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL,
        "archivedAt" DATETIME,
        CONSTRAINT "DanceGroup_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "DanceGroup_coachId_fkey" FOREIGN KEY ("coachId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
        CONSTRAINT "DanceGroup_assistantCoachId_fkey" FOREIGN KEY ("assistantCoachId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
      )`,
      `CREATE TABLE "Enrollment" (
        "id" TEXT NOT NULL PRIMARY KEY, "studentId" TEXT NOT NULL, "groupId" TEXT NOT NULL,
        "joinedAt" DATETIME NOT NULL, "leftAt" DATETIME, "status" TEXT NOT NULL DEFAULT 'ACTIVE',
        "notes" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "Enrollment_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT "Enrollment_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "DanceGroup" ("id") ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      `CREATE TABLE "WeeklySchedule" (
        "id" TEXT NOT NULL PRIMARY KEY, "groupId" TEXT NOT NULL, "branchId" TEXT NOT NULL,
        "weekday" INTEGER NOT NULL, "startTime" TEXT NOT NULL, "endTime" TEXT NOT NULL,
        "room" TEXT, "coachId" TEXT, "validFrom" DATETIME NOT NULL, "validTo" DATETIME,
        "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "WeeklySchedule_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "DanceGroup" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT "WeeklySchedule_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "WeeklySchedule_coachId_fkey" FOREIGN KEY ("coachId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
      )`,
      `CREATE TABLE "Lesson" (
        "id" TEXT NOT NULL PRIMARY KEY, "groupId" TEXT NOT NULL, "branchId" TEXT NOT NULL,
        "coachId" TEXT, "scheduleTemplateId" TEXT, "startsAt" DATETIME NOT NULL,
        "endsAt" DATETIME NOT NULL, "room" TEXT, "status" TEXT NOT NULL DEFAULT 'PLANNED',
        "cancellationReason" TEXT, "notes" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "Lesson_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "DanceGroup" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "Lesson_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "Lesson_coachId_fkey" FOREIGN KEY ("coachId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
        CONSTRAINT "Lesson_scheduleTemplateId_fkey" FOREIGN KEY ("scheduleTemplateId") REFERENCES "WeeklySchedule" ("id") ON DELETE SET NULL ON UPDATE CASCADE
      )`,
      `CREATE TABLE "Attendance" (
        "lessonId" TEXT NOT NULL, "studentId" TEXT NOT NULL, "status" TEXT NOT NULL,
        "markedByUserId" TEXT NOT NULL, "markedAt" DATETIME NOT NULL, "comment" TEXT,
        PRIMARY KEY ("lessonId", "studentId"),
        CONSTRAINT "Attendance_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lesson" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT "Attendance_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT "Attendance_markedByUserId_fkey" FOREIGN KEY ("markedByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "AuditLog" (
        "id" TEXT NOT NULL PRIMARY KEY, "actorUserId" TEXT NOT NULL, "action" TEXT NOT NULL,
        "entityType" TEXT NOT NULL, "entityId" TEXT NOT NULL, "detail" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "AuditLog_actorUserId_fkey" FOREIGN KEY ("actorUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      'CREATE INDEX "DanceGroup_branchId_status_idx" ON "DanceGroup"("branchId", "status")',
      'CREATE INDEX "DanceGroup_coachId_idx" ON "DanceGroup"("coachId")',
      'CREATE INDEX "DanceGroup_assistantCoachId_idx" ON "DanceGroup"("assistantCoachId")',
      'CREATE INDEX "DanceGroup_name_idx" ON "DanceGroup"("name")',
      'CREATE INDEX "DanceGroup_direction_idx" ON "DanceGroup"("direction")',
      'CREATE INDEX "DanceGroup_archivedAt_idx" ON "DanceGroup"("archivedAt")',
      'CREATE INDEX "Enrollment_studentId_status_idx" ON "Enrollment"("studentId", "status")',
      'CREATE INDEX "Enrollment_groupId_status_idx" ON "Enrollment"("groupId", "status")',
      'CREATE INDEX "Enrollment_groupId_leftAt_idx" ON "Enrollment"("groupId", "leftAt")',
      'CREATE INDEX "WeeklySchedule_branchId_weekday_isActive_idx" ON "WeeklySchedule"("branchId", "weekday", "isActive")',
      'CREATE INDEX "WeeklySchedule_groupId_isActive_idx" ON "WeeklySchedule"("groupId", "isActive")',
      'CREATE INDEX "WeeklySchedule_coachId_weekday_isActive_idx" ON "WeeklySchedule"("coachId", "weekday", "isActive")',
      'CREATE INDEX "WeeklySchedule_room_weekday_isActive_idx" ON "WeeklySchedule"("room", "weekday", "isActive")',
      'CREATE INDEX "Lesson_branchId_startsAt_idx" ON "Lesson"("branchId", "startsAt")',
      'CREATE INDEX "Lesson_coachId_startsAt_idx" ON "Lesson"("coachId", "startsAt")',
      'CREATE INDEX "Lesson_scheduleTemplateId_idx" ON "Lesson"("scheduleTemplateId")',
      'CREATE INDEX "Lesson_status_startsAt_idx" ON "Lesson"("status", "startsAt")',
      'CREATE UNIQUE INDEX "Lesson_groupId_startsAt_key" ON "Lesson"("groupId", "startsAt")',
      'CREATE INDEX "Attendance_studentId_markedAt_idx" ON "Attendance"("studentId", "markedAt")',
      'CREATE INDEX "Attendance_markedByUserId_idx" ON "Attendance"("markedByUserId")',
      'CREATE INDEX "Attendance_status_idx" ON "Attendance"("status")',
      'CREATE INDEX "AuditLog_actorUserId_createdAt_idx" ON "AuditLog"("actorUserId", "createdAt")',
      'CREATE INDEX "AuditLog_entityType_entityId_createdAt_idx" ON "AuditLog"("entityType", "entityId", "createdAt")',
      'CREATE INDEX "AuditLog_action_createdAt_idx" ON "AuditLog"("action", "createdAt")',
    ],
  },
  {
    id: '20260806000000_sprint_3',
    statements: [
      `CREATE TABLE "Tariff" (
        "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "branchId" TEXT,
        "type" TEXT NOT NULL, "lessonCount" INTEGER, "validityDays" INTEGER,
        "price" INTEGER NOT NULL, "currency" TEXT NOT NULL DEFAULT 'RUB', "freezeDays" INTEGER,
        "isActive" BOOLEAN NOT NULL DEFAULT true, "description" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL,
        "archivedAt" DATETIME,
        CONSTRAINT "Tariff_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "Subscription" (
        "id" TEXT NOT NULL PRIMARY KEY, "studentId" TEXT NOT NULL, "tariffId" TEXT NOT NULL,
        "branchId" TEXT NOT NULL, "purchasedAt" DATETIME NOT NULL, "startsAt" DATETIME NOT NULL,
        "expiresAt" DATETIME, "lessonLimit" INTEGER, "lessonsUsed" INTEGER NOT NULL DEFAULT 0,
        "status" TEXT NOT NULL DEFAULT 'PENDING', "freezeStartedAt" DATETIME, "freezeEndsAt" DATETIME,
        "frozenDaysUsed" INTEGER NOT NULL DEFAULT 0, "salePrice" INTEGER NOT NULL, "notes" TEXT,
        "createdByUserId" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "Subscription_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "Subscription_tariffId_fkey" FOREIGN KEY ("tariffId") REFERENCES "Tariff" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "Subscription_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "Subscription_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "Payment" (
        "id" TEXT NOT NULL PRIMARY KEY, "studentId" TEXT NOT NULL, "subscriptionId" TEXT,
        "branchId" TEXT NOT NULL, "amount" INTEGER NOT NULL, "paymentMethod" TEXT NOT NULL,
        "status" TEXT NOT NULL DEFAULT 'COMPLETED', "paidAt" DATETIME NOT NULL, "comment" TEXT,
        "externalReference" TEXT, "createdByUserId" TEXT NOT NULL,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "Payment_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "Payment_subscriptionId_fkey" FOREIGN KEY ("subscriptionId") REFERENCES "Subscription" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "Payment_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "Payment_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "Refund" (
        "id" TEXT NOT NULL PRIMARY KEY, "paymentId" TEXT NOT NULL, "amount" INTEGER NOT NULL,
        "reason" TEXT NOT NULL, "refundedAt" DATETIME NOT NULL, "createdByUserId" TEXT NOT NULL,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Refund_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "Refund_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "SubscriptionLedger" (
        "id" TEXT NOT NULL PRIMARY KEY, "subscriptionId" TEXT NOT NULL, "studentId" TEXT NOT NULL,
        "lessonId" TEXT, "attendanceId" TEXT, "type" TEXT NOT NULL,
        "lessonDelta" INTEGER NOT NULL DEFAULT 0, "amountDelta" INTEGER, "comment" TEXT,
        "createdByUserId" TEXT, "reversesLedgerId" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "SubscriptionLedger_subscriptionId_fkey" FOREIGN KEY ("subscriptionId") REFERENCES "Subscription" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "SubscriptionLedger_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "SubscriptionLedger_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lesson" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "SubscriptionLedger_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
        CONSTRAINT "SubscriptionLedger_reversesLedgerId_fkey" FOREIGN KEY ("reversesLedgerId") REFERENCES "SubscriptionLedger" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      'CREATE INDEX "Tariff_branchId_isActive_idx" ON "Tariff"("branchId", "isActive")',
      'CREATE INDEX "Tariff_type_isActive_idx" ON "Tariff"("type", "isActive")',
      'CREATE INDEX "Tariff_name_idx" ON "Tariff"("name")',
      'CREATE INDEX "Tariff_archivedAt_idx" ON "Tariff"("archivedAt")',
      'CREATE INDEX "Subscription_studentId_status_idx" ON "Subscription"("studentId", "status")',
      'CREATE INDEX "Subscription_branchId_status_idx" ON "Subscription"("branchId", "status")',
      'CREATE INDEX "Subscription_tariffId_idx" ON "Subscription"("tariffId")',
      'CREATE INDEX "Subscription_startsAt_expiresAt_idx" ON "Subscription"("startsAt", "expiresAt")',
      'CREATE INDEX "Subscription_createdByUserId_idx" ON "Subscription"("createdByUserId")',
      'CREATE INDEX "Payment_studentId_paidAt_idx" ON "Payment"("studentId", "paidAt")',
      'CREATE INDEX "Payment_subscriptionId_idx" ON "Payment"("subscriptionId")',
      'CREATE INDEX "Payment_branchId_paidAt_idx" ON "Payment"("branchId", "paidAt")',
      'CREATE INDEX "Payment_paymentMethod_paidAt_idx" ON "Payment"("paymentMethod", "paidAt")',
      'CREATE INDEX "Payment_status_paidAt_idx" ON "Payment"("status", "paidAt")',
      'CREATE INDEX "Payment_createdByUserId_paidAt_idx" ON "Payment"("createdByUserId", "paidAt")',
      'CREATE INDEX "Payment_externalReference_idx" ON "Payment"("externalReference")',
      'CREATE INDEX "Refund_paymentId_refundedAt_idx" ON "Refund"("paymentId", "refundedAt")',
      'CREATE INDEX "Refund_createdByUserId_refundedAt_idx" ON "Refund"("createdByUserId", "refundedAt")',
      'CREATE UNIQUE INDEX "SubscriptionLedger_reversesLedgerId_key" ON "SubscriptionLedger"("reversesLedgerId")',
      'CREATE INDEX "SubscriptionLedger_subscriptionId_createdAt_idx" ON "SubscriptionLedger"("subscriptionId", "createdAt")',
      'CREATE INDEX "SubscriptionLedger_studentId_createdAt_idx" ON "SubscriptionLedger"("studentId", "createdAt")',
      'CREATE INDEX "SubscriptionLedger_lessonId_idx" ON "SubscriptionLedger"("lessonId")',
      'CREATE INDEX "SubscriptionLedger_attendanceId_type_idx" ON "SubscriptionLedger"("attendanceId", "type")',
      'CREATE INDEX "SubscriptionLedger_createdByUserId_idx" ON "SubscriptionLedger"("createdByUserId")',
    ],
  },
  {
    id: '20260807000000_sprint_4',
    statements: [
      `CREATE TABLE "ExpenseCategory" (
        "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "branchId" TEXT,
        "description" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT true,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, "archivedAt" DATETIME,
        CONSTRAINT "ExpenseCategory_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "Expense" (
        "id" TEXT NOT NULL PRIMARY KEY, "branchId" TEXT NOT NULL, "categoryId" TEXT NOT NULL,
        "amount" INTEGER NOT NULL, "spentAt" DATETIME NOT NULL, "paymentMethod" TEXT NOT NULL,
        "vendor" TEXT, "description" TEXT NOT NULL, "documentNumber" TEXT, "attachmentPath" TEXT,
        "status" TEXT NOT NULL DEFAULT 'DRAFT', "createdByUserId" TEXT NOT NULL, "confirmedByUserId" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "Expense_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "Expense_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "ExpenseCategory" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "Expense_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "Expense_confirmedByUserId_fkey" FOREIGN KEY ("confirmedByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "CashRegister" (
        "id" TEXT NOT NULL PRIMARY KEY, "branchId" TEXT NOT NULL, "name" TEXT NOT NULL,
        "type" TEXT NOT NULL, "openingBalance" INTEGER NOT NULL DEFAULT 0, "isActive" BOOLEAN NOT NULL DEFAULT true,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "CashRegister_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "CashTransaction" (
        "id" TEXT NOT NULL PRIMARY KEY, "cashRegisterId" TEXT NOT NULL, "branchId" TEXT NOT NULL,
        "type" TEXT NOT NULL, "amount" INTEGER NOT NULL, "sourceType" TEXT NOT NULL, "sourceId" TEXT,
        "occurredAt" DATETIME NOT NULL, "comment" TEXT, "createdByUserId" TEXT NOT NULL,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "CashTransaction_cashRegisterId_fkey" FOREIGN KEY ("cashRegisterId") REFERENCES "CashRegister" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "CashTransaction_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "CashTransaction_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "PayrollRule" (
        "id" TEXT NOT NULL PRIMARY KEY, "coachId" TEXT NOT NULL, "branchId" TEXT NOT NULL, "groupId" TEXT,
        "type" TEXT NOT NULL, "fixedAmount" INTEGER, "amountPerAttendee" INTEGER, "percent" REAL, "monthlyAmount" INTEGER,
        "validFrom" DATETIME NOT NULL, "validTo" DATETIME, "isActive" BOOLEAN NOT NULL DEFAULT true,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "PayrollRule_coachId_fkey" FOREIGN KEY ("coachId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "PayrollRule_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "PayrollRule_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "DanceGroup" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "PayrollPeriod" (
        "id" TEXT NOT NULL PRIMARY KEY, "dateFrom" DATETIME NOT NULL, "dateTo" DATETIME NOT NULL, "branchId" TEXT,
        "status" TEXT NOT NULL DEFAULT 'DRAFT', "createdByUserId" TEXT NOT NULL, "approvedByUserId" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "PayrollPeriod_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "PayrollPeriod_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "PayrollPeriod_approvedByUserId_fkey" FOREIGN KEY ("approvedByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "PayrollAccrual" (
        "id" TEXT NOT NULL PRIMARY KEY, "payrollPeriodId" TEXT NOT NULL, "coachId" TEXT NOT NULL, "branchId" TEXT NOT NULL,
        "groupId" TEXT, "lessonId" TEXT, "type" TEXT NOT NULL, "baseAmount" INTEGER NOT NULL, "attendeeCount" INTEGER,
        "revenueBase" INTEGER, "calculatedAmount" INTEGER NOT NULL, "manualAdjustment" INTEGER NOT NULL DEFAULT 0,
        "finalAmount" INTEGER NOT NULL, "comment" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "PayrollAccrual_payrollPeriodId_fkey" FOREIGN KEY ("payrollPeriodId") REFERENCES "PayrollPeriod" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "PayrollAccrual_coachId_fkey" FOREIGN KEY ("coachId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "PayrollAccrual_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "PayrollAccrual_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "DanceGroup" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "PayrollAccrual_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lesson" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      'CREATE INDEX "ExpenseCategory_branchId_isActive_idx" ON "ExpenseCategory"("branchId", "isActive")',
      'CREATE INDEX "ExpenseCategory_name_idx" ON "ExpenseCategory"("name")',
      'CREATE INDEX "ExpenseCategory_archivedAt_idx" ON "ExpenseCategory"("archivedAt")',
      'CREATE INDEX "Expense_branchId_spentAt_idx" ON "Expense"("branchId", "spentAt")',
      'CREATE INDEX "Expense_categoryId_spentAt_idx" ON "Expense"("categoryId", "spentAt")',
      'CREATE INDEX "Expense_status_spentAt_idx" ON "Expense"("status", "spentAt")',
      'CREATE INDEX "Expense_paymentMethod_spentAt_idx" ON "Expense"("paymentMethod", "spentAt")',
      'CREATE INDEX "Expense_createdByUserId_spentAt_idx" ON "Expense"("createdByUserId", "spentAt")',
      'CREATE INDEX "Expense_documentNumber_idx" ON "Expense"("documentNumber")',
      'CREATE INDEX "CashRegister_branchId_isActive_idx" ON "CashRegister"("branchId", "isActive")',
      'CREATE INDEX "CashRegister_type_isActive_idx" ON "CashRegister"("type", "isActive")',
      'CREATE INDEX "CashTransaction_cashRegisterId_occurredAt_idx" ON "CashTransaction"("cashRegisterId", "occurredAt")',
      'CREATE INDEX "CashTransaction_branchId_occurredAt_idx" ON "CashTransaction"("branchId", "occurredAt")',
      'CREATE INDEX "CashTransaction_sourceType_sourceId_idx" ON "CashTransaction"("sourceType", "sourceId")',
      'CREATE INDEX "CashTransaction_createdByUserId_occurredAt_idx" ON "CashTransaction"("createdByUserId", "occurredAt")',
      'CREATE INDEX "PayrollRule_coachId_branchId_groupId_isActive_idx" ON "PayrollRule"("coachId", "branchId", "groupId", "isActive")',
      'CREATE INDEX "PayrollRule_validFrom_validTo_idx" ON "PayrollRule"("validFrom", "validTo")',
      'CREATE INDEX "PayrollPeriod_branchId_dateFrom_dateTo_idx" ON "PayrollPeriod"("branchId", "dateFrom", "dateTo")',
      'CREATE INDEX "PayrollPeriod_status_dateFrom_idx" ON "PayrollPeriod"("status", "dateFrom")',
      'CREATE UNIQUE INDEX "PayrollAccrual_payrollPeriodId_coachId_lessonId_type_key" ON "PayrollAccrual"("payrollPeriodId", "coachId", "lessonId", "type")',
      'CREATE INDEX "PayrollAccrual_payrollPeriodId_coachId_idx" ON "PayrollAccrual"("payrollPeriodId", "coachId")',
      'CREATE INDEX "PayrollAccrual_branchId_coachId_idx" ON "PayrollAccrual"("branchId", "coachId")',
      'CREATE INDEX "PayrollAccrual_lessonId_idx" ON "PayrollAccrual"("lessonId")',
    ],
  },
  {
    id: '20260809000000_sprint_4_1a',
    statements: [
      `UPDATE "User" SET "role" = 'ADMIN' WHERE "role" = 'BRANCH_MANAGER'`,
      'ALTER TABLE "User" ADD COLUMN "phone" TEXT',
      'ALTER TABLE "User" ADD COLUMN "failedLoginAttempts" INTEGER NOT NULL DEFAULT 0',
      'ALTER TABLE "User" ADD COLUMN "lockedUntil" DATETIME',
      'ALTER TABLE "User" ADD COLUMN "lastLoginAt" DATETIME',
      'ALTER TABLE "User" ADD COLUMN "passwordChangedAt" DATETIME',
      'ALTER TABLE "User" ADD COLUMN "securityVersion" INTEGER NOT NULL DEFAULT 1',
      'ALTER TABLE "User" ADD COLUMN "recoveryCodeHash" TEXT',
      'ALTER TABLE "User" ADD COLUMN "recoveryCodeCreatedAt" DATETIME',
      'ALTER TABLE "User" ADD COLUMN "recoveryFailedAttempts" INTEGER NOT NULL DEFAULT 0',
      'ALTER TABLE "User" ADD COLUMN "recoveryLockedUntil" DATETIME',
      'ALTER TABLE "Session" ADD COLUMN "securityVersion" INTEGER NOT NULL DEFAULT 1',
      'CREATE INDEX "User_lockedUntil_idx" ON "User"("lockedUntil")',
      'CREATE INDEX "Session_userId_securityVersion_idx" ON "Session"("userId", "securityVersion")',
    ],
  },
  {
    id: '20260809010000_sprint_4_1b',
    statements: [
      'ALTER TABLE "Branch" ADD COLUMN "archivedAt" DATETIME',
      `CREATE TABLE "Room" (
        "id" TEXT NOT NULL PRIMARY KEY, "branchId" TEXT NOT NULL, "name" TEXT NOT NULL,
        "capacity" INTEGER, "description" TEXT, "floor" TEXT, "areaSquareMeters" REAL,
        "colorKey" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT true, "archivedAt" DATETIME,
        "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "Room_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      'ALTER TABLE "WeeklySchedule" ADD COLUMN "roomId" TEXT REFERENCES "Room"("id") ON DELETE SET NULL ON UPDATE CASCADE',
      'ALTER TABLE "Lesson" ADD COLUMN "roomId" TEXT REFERENCES "Room"("id") ON DELETE SET NULL ON UPDATE CASCADE',
      `CREATE TABLE "RoomRental" (
        "id" TEXT NOT NULL PRIMARY KEY, "branchId" TEXT NOT NULL, "roomId" TEXT NOT NULL,
        "startAt" DATETIME NOT NULL, "endAt" DATETIME NOT NULL, "clientName" TEXT, "phone" TEXT,
        "amount" INTEGER, "comment" TEXT, "status" TEXT NOT NULL DEFAULT 'ACTIVE',
        "createdByUserId" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "RoomRental_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "RoomRental_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "Room" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "RoomRental_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "RoomClosure" (
        "id" TEXT NOT NULL PRIMARY KEY, "roomId" TEXT NOT NULL, "startAt" DATETIME NOT NULL,
        "endAt" DATETIME NOT NULL, "reason" TEXT NOT NULL, "comment" TEXT, "createdByUserId" TEXT NOT NULL,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "RoomClosure_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "Room" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "RoomClosure_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "CalendarException" (
        "id" TEXT NOT NULL PRIMARY KEY, "branchId" TEXT, "startAt" DATETIME NOT NULL,
        "endAt" DATETIME NOT NULL, "type" TEXT NOT NULL, "title" TEXT NOT NULL, "comment" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "CalendarException_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "TrainerSubstitution" (
        "id" TEXT NOT NULL PRIMARY KEY, "lessonId" TEXT NOT NULL, "originalTrainerId" TEXT,
        "substituteTrainerId" TEXT NOT NULL, "reason" TEXT, "createdByUserId" TEXT NOT NULL,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "TrainerSubstitution_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lesson" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "TrainerSubstitution_originalTrainerId_fkey" FOREIGN KEY ("originalTrainerId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
        CONSTRAINT "TrainerSubstitution_substituteTrainerId_fkey" FOREIGN KEY ("substituteTrainerId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "TrainerSubstitution_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      'CREATE UNIQUE INDEX "Room_branchId_name_key" ON "Room"("branchId", "name")',
      'CREATE INDEX "Room_branchId_isActive_sortOrder_idx" ON "Room"("branchId", "isActive", "sortOrder")',
      'CREATE INDEX "Room_archivedAt_idx" ON "Room"("archivedAt")',
      'CREATE INDEX "Branch_archivedAt_idx" ON "Branch"("archivedAt")',
      'CREATE INDEX "WeeklySchedule_roomId_weekday_isActive_idx" ON "WeeklySchedule"("roomId", "weekday", "isActive")',
      'CREATE INDEX "Lesson_roomId_startsAt_idx" ON "Lesson"("roomId", "startsAt")',
      'CREATE INDEX "Lesson_groupId_startsAt_idx" ON "Lesson"("groupId", "startsAt")',
      'CREATE INDEX "RoomRental_branchId_startAt_idx" ON "RoomRental"("branchId", "startAt")',
      'CREATE INDEX "RoomRental_roomId_startAt_endAt_idx" ON "RoomRental"("roomId", "startAt", "endAt")',
      'CREATE INDEX "RoomRental_status_startAt_idx" ON "RoomRental"("status", "startAt")',
      'CREATE INDEX "RoomClosure_roomId_startAt_endAt_idx" ON "RoomClosure"("roomId", "startAt", "endAt")',
      'CREATE INDEX "CalendarException_branchId_startAt_endAt_idx" ON "CalendarException"("branchId", "startAt", "endAt")',
      'CREATE INDEX "CalendarException_type_startAt_idx" ON "CalendarException"("type", "startAt")',
      'CREATE UNIQUE INDEX "TrainerSubstitution_lessonId_key" ON "TrainerSubstitution"("lessonId")',
      'CREATE INDEX "TrainerSubstitution_substituteTrainerId_createdAt_idx" ON "TrainerSubstitution"("substituteTrainerId", "createdAt")',
    ],
  },
  {
    id: '20260809020000_sprint_4_1c',
    statements: [
      `CREATE TABLE "MembershipCard" (
        "id" TEXT NOT NULL PRIMARY KEY, "barcode" TEXT NOT NULL, "studentId" TEXT,
        "status" TEXT NOT NULL DEFAULT 'FREE', "issuedAt" DATETIME, "unassignedAt" DATETIME,
        "blockedAt" DATETIME, "archivedAt" DATETIME, "notes" TEXT,
        "createdByUserId" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "MembershipCard_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "MembershipCard_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "CardEvent" (
        "id" TEXT NOT NULL PRIMARY KEY, "cardId" TEXT NOT NULL, "studentId" TEXT,
        "eventType" TEXT NOT NULL, "performedByUserId" TEXT, "relatedCardId" TEXT,
        "occurredAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "comment" TEXT,
        CONSTRAINT "CardEvent_cardId_fkey" FOREIGN KEY ("cardId") REFERENCES "MembershipCard" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "CardEvent_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "CardEvent_performedByUserId_fkey" FOREIGN KEY ("performedByUserId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
        CONSTRAINT "CardEvent_relatedCardId_fkey" FOREIGN KEY ("relatedCardId") REFERENCES "MembershipCard" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "CardScanEvent" (
        "id" TEXT NOT NULL PRIMARY KEY, "barcode" TEXT NOT NULL, "cardId" TEXT,
        "studentId" TEXT, "performedByUserId" TEXT, "result" TEXT NOT NULL,
        "occurredAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "CardScanEvent_cardId_fkey" FOREIGN KEY ("cardId") REFERENCES "MembershipCard" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "CardScanEvent_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "CardScanEvent_performedByUserId_fkey" FOREIGN KEY ("performedByUserId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
      )`,
      'CREATE UNIQUE INDEX "MembershipCard_barcode_key" ON "MembershipCard"("barcode")',
      `CREATE UNIQUE INDEX "MembershipCard_studentId_assigned_key" ON "MembershipCard"("studentId") WHERE "status" = 'ASSIGNED'`,
      'CREATE INDEX "MembershipCard_studentId_status_idx" ON "MembershipCard"("studentId", "status")',
      'CREATE INDEX "MembershipCard_status_createdAt_idx" ON "MembershipCard"("status", "createdAt")',
      'CREATE INDEX "MembershipCard_createdByUserId_idx" ON "MembershipCard"("createdByUserId")',
      'CREATE INDEX "CardEvent_cardId_occurredAt_idx" ON "CardEvent"("cardId", "occurredAt")',
      'CREATE INDEX "CardEvent_studentId_occurredAt_idx" ON "CardEvent"("studentId", "occurredAt")',
      'CREATE INDEX "CardEvent_performedByUserId_occurredAt_idx" ON "CardEvent"("performedByUserId", "occurredAt")',
      'CREATE INDEX "CardEvent_eventType_occurredAt_idx" ON "CardEvent"("eventType", "occurredAt")',
      'CREATE INDEX "CardScanEvent_barcode_occurredAt_idx" ON "CardScanEvent"("barcode", "occurredAt")',
      'CREATE INDEX "CardScanEvent_cardId_occurredAt_idx" ON "CardScanEvent"("cardId", "occurredAt")',
      'CREATE INDEX "CardScanEvent_studentId_occurredAt_idx" ON "CardScanEvent"("studentId", "occurredAt")',
      'CREATE INDEX "CardScanEvent_performedByUserId_occurredAt_idx" ON "CardScanEvent"("performedByUserId", "occurredAt")',
      'CREATE INDEX "CardScanEvent_result_occurredAt_idx" ON "CardScanEvent"("result", "occurredAt")',
    ],
  },
  {
    id: '20260811000000_sprint_4_1d',
    statements: [
      'ALTER TABLE "Lesson" ADD COLUMN "attendanceCompletedAt" DATETIME',
      'CREATE INDEX "Lesson_attendanceCompletedAt_idx" ON "Lesson"("attendanceCompletedAt")',
    ],
  },
  {
    id: '20260811010000_sprint_4_2a',
    statements: [
      `CREATE TABLE "StudentNote" (
        "id" TEXT NOT NULL PRIMARY KEY, "studentId" TEXT NOT NULL, "authorUserId" TEXT NOT NULL,
        "text" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL, "archivedAt" DATETIME,
        CONSTRAINT "StudentNote_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT "StudentNote_authorUserId_fkey" FOREIGN KEY ("authorUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      'CREATE INDEX "StudentNote_studentId_archivedAt_createdAt_idx" ON "StudentNote"("studentId", "archivedAt", "createdAt")',
      'CREATE INDEX "StudentNote_authorUserId_createdAt_idx" ON "StudentNote"("authorUserId", "createdAt")',
      'ALTER TABLE "StudentContact" ADD COLUMN "archivedAt" DATETIME',
      'DROP INDEX "StudentContact_studentId_idx"',
      'CREATE INDEX "StudentContact_studentId_archivedAt_idx" ON "StudentContact"("studentId", "archivedAt")',
    ],
  },
  {
    id: '20260818000000_sprint_4_4a',
    statements: [
      `CREATE TABLE "SyncOutbox" (
        "id" TEXT NOT NULL PRIMARY KEY, "entityType" TEXT NOT NULL, "entityId" TEXT NOT NULL,
        "operation" TEXT NOT NULL DEFAULT 'UPSERT', "payloadVersion" INTEGER NOT NULL DEFAULT 1,
        "payloadJson" TEXT NOT NULL DEFAULT '{}', "idempotencyKey" TEXT NOT NULL,
        "status" TEXT NOT NULL DEFAULT 'PENDING', "attemptCount" INTEGER NOT NULL DEFAULT 0,
        "nextAttemptAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastAttemptAt" DATETIME,
        "lastErrorCode" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL, "syncedAt" DATETIME
      )`,
      `CREATE TABLE "SyncLog" (
        "id" TEXT NOT NULL PRIMARY KEY, "outboxId" TEXT, "entityType" TEXT, "entityId" TEXT,
        "operation" TEXT, "result" TEXT NOT NULL, "attemptCount" INTEGER NOT NULL DEFAULT 0,
        "errorCode" TEXT, "message" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      )`,
      'CREATE UNIQUE INDEX "SyncOutbox_idempotencyKey_key" ON "SyncOutbox"("idempotencyKey")',
      'CREATE INDEX "SyncOutbox_status_nextAttemptAt_createdAt_idx" ON "SyncOutbox"("status", "nextAttemptAt", "createdAt")',
      'CREATE INDEX "SyncOutbox_entityType_entityId_createdAt_idx" ON "SyncOutbox"("entityType", "entityId", "createdAt")',
      'CREATE INDEX "SyncLog_createdAt_idx" ON "SyncLog"("createdAt")',
      'CREATE INDEX "SyncLog_result_createdAt_idx" ON "SyncLog"("result", "createdAt")',
      `CREATE TRIGGER "sync_branch_insert" AFTER INSERT ON "Branch" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'BRANCH', NEW."id", 'UPSERT', lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_branch_update" AFTER UPDATE ON "Branch" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'BRANCH', NEW."id", CASE WHEN NEW."archivedAt" IS NOT NULL OR NEW."isActive" = false THEN 'ARCHIVE' ELSE 'UPSERT' END, lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_room_insert" AFTER INSERT ON "Room" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'ROOM', NEW."id", 'UPSERT', lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_room_update" AFTER UPDATE ON "Room" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'ROOM', NEW."id", CASE WHEN NEW."archivedAt" IS NOT NULL OR NEW."isActive" = false THEN 'ARCHIVE' ELSE 'UPSERT' END, lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_trainer_insert" AFTER INSERT ON "User" WHEN NEW."role" = 'COACH' BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'TRAINER', NEW."id", 'UPSERT', lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_trainer_update" AFTER UPDATE ON "User" WHEN OLD."role" = 'COACH' OR NEW."role" = 'COACH' BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'TRAINER', NEW."id", CASE WHEN NEW."role" != 'COACH' OR NEW."isActive" = false THEN 'ARCHIVE' ELSE 'UPSERT' END, lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_group_insert" AFTER INSERT ON "DanceGroup" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'GROUP', NEW."id", 'UPSERT', lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_group_update" AFTER UPDATE ON "DanceGroup" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'GROUP', NEW."id", CASE WHEN NEW."archivedAt" IS NOT NULL OR NEW."status" = 'ARCHIVED' THEN 'ARCHIVE' ELSE 'UPSERT' END, lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_student_insert" AFTER INSERT ON "Student" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'STUDENT_IDENTITY', NEW."id", 'UPSERT', lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_student_update" AFTER UPDATE ON "Student" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'STUDENT_IDENTITY', NEW."id", CASE WHEN NEW."archivedAt" IS NOT NULL OR NEW."status" = 'ARCHIVED' THEN 'ARCHIVE' ELSE 'UPSERT' END, lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_enrollment_insert" AFTER INSERT ON "Enrollment" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'GROUP_MEMBERSHIP', NEW."id", 'UPSERT', lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_enrollment_update" AFTER UPDATE ON "Enrollment" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'GROUP_MEMBERSHIP', NEW."id", CASE WHEN NEW."status" = 'LEFT' OR NEW."leftAt" IS NOT NULL THEN 'ARCHIVE' ELSE 'UPSERT' END, lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_schedule_insert" AFTER INSERT ON "WeeklySchedule" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'SCHEDULE', NEW."id", 'UPSERT', lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_schedule_update" AFTER UPDATE ON "WeeklySchedule" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'SCHEDULE', NEW."id", CASE WHEN NEW."isActive" = false THEN 'ARCHIVE' ELSE 'UPSERT' END, lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_lesson_insert" AFTER INSERT ON "Lesson" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'LESSON', NEW."id", 'UPSERT', lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
      `CREATE TRIGGER "sync_lesson_update" AFTER UPDATE ON "Lesson" BEGIN INSERT INTO "SyncOutbox" ("id", "entityType", "entityId", "operation", "idempotencyKey", "updatedAt") VALUES (lower(hex(randomblob(16))), 'LESSON', NEW."id", CASE WHEN NEW."status" = 'CANCELLED' THEN 'ARCHIVE' ELSE 'UPSERT' END, lower(hex(randomblob(16))), CURRENT_TIMESTAMP); END`,
    ],
  },
  {
    id: '20260818020000_sprint_4_4d',
    statements: [
      `CREATE TABLE "Publication" (
        "id" TEXT NOT NULL PRIMARY KEY, "type" TEXT NOT NULL, "title" TEXT NOT NULL,
        "body" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'DRAFT', "audienceMode" TEXT NOT NULL,
        "mediaLocalPath" TEXT, "mediaFileName" TEXT, "mediaContentType" TEXT, "mediaRef" TEXT,
        "publishAt" DATETIME, "expiresAt" DATETIME, "eventStartsAt" DATETIME,
        "eventLocation" TEXT, "createdByUserId" TEXT NOT NULL,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL,
        "archivedAt" DATETIME,
        CONSTRAINT "Publication_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
      )`,
      `CREATE TABLE "PublicationAudienceTarget" (
        "publicationId" TEXT NOT NULL, "type" TEXT NOT NULL, "targetId" TEXT NOT NULL,
        PRIMARY KEY ("publicationId", "type", "targetId"),
        CONSTRAINT "PublicationAudienceTarget_publicationId_fkey" FOREIGN KEY ("publicationId") REFERENCES "Publication" ("id") ON DELETE CASCADE ON UPDATE CASCADE
      )`,
      'CREATE INDEX "Publication_status_publishAt_createdAt_idx" ON "Publication"("status", "publishAt", "createdAt")',
      'CREATE INDEX "Publication_createdByUserId_idx" ON "Publication"("createdByUserId")',
      'CREATE INDEX "PublicationAudienceTarget_type_targetId_idx" ON "PublicationAudienceTarget"("type", "targetId")',
    ],
  },
  {
    id: '20260818030000_sprint_4_5a',
    statements: [
      'ALTER TABLE "SyncOutbox" ADD COLUMN "baseRevision" INTEGER NOT NULL DEFAULT 0',
      'CREATE TABLE "SyncEntityState" (\n  "entityType" TEXT NOT NULL,\n  "entityId" TEXT NOT NULL,\n  "revision" INTEGER NOT NULL,\n  "serverSequence" INTEGER NOT NULL,\n  "sourceDeviceId" TEXT NOT NULL,\n  "serverUpdatedAt" DATETIME NOT NULL,\n  "updatedAt" DATETIME NOT NULL,\n  PRIMARY KEY ("entityType", "entityId")\n)',
      'CREATE INDEX "SyncEntityState_serverSequence_idx" ON "SyncEntityState"("serverSequence")',
      'CREATE TABLE "SyncConflict" (\n  "id" TEXT NOT NULL PRIMARY KEY,\n  "serverConflictId" TEXT,\n  "entityType" TEXT NOT NULL,\n  "entityId" TEXT NOT NULL,\n  "baseRevision" INTEGER NOT NULL,\n  "canonicalRevision" INTEGER NOT NULL,\n  "canonicalOperation" TEXT NOT NULL,\n  "canonicalPayloadJson" TEXT NOT NULL,\n  "candidateOperation" TEXT NOT NULL,\n  "candidatePayloadJson" TEXT NOT NULL,\n  "sourceDeviceId" TEXT,\n  "status" TEXT NOT NULL DEFAULT \'OPEN\',\n  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  "resolvedAt" DATETIME\n)',
      'CREATE UNIQUE INDEX "SyncConflict_serverConflictId_key" ON "SyncConflict"("serverConflictId")',
      'CREATE INDEX "SyncConflict_status_createdAt_idx" ON "SyncConflict"("status","createdAt")',
      'CREATE INDEX "SyncConflict_entityType_entityId_status_idx" ON "SyncConflict"("entityType","entityId","status")',
      'DROP TRIGGER IF EXISTS "sync_branch_insert"',
      'CREATE TRIGGER "sync_branch_insert" AFTER INSERT ON "Branch" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'BRANCH\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'BRANCH\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_branch_update"',
      'CREATE TRIGGER "sync_branch_update" AFTER UPDATE ON "Branch" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'BRANCH\', NEW."id", CASE WHEN NEW."archivedAt" IS NOT NULL THEN \'ARCHIVE\' ELSE \'UPSERT\' END, lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'BRANCH\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_room_insert"',
      'CREATE TRIGGER "sync_room_insert" AFTER INSERT ON "Room" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'ROOM\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'ROOM\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_room_update"',
      'CREATE TRIGGER "sync_room_update" AFTER UPDATE ON "Room" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'ROOM\', NEW."id", CASE WHEN NEW."archivedAt" IS NOT NULL THEN \'ARCHIVE\' ELSE \'UPSERT\' END, lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'ROOM\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_trainer_insert"',
      'CREATE TRIGGER "sync_trainer_insert" AFTER INSERT ON "User" WHEN (NEW."role" = \'COACH\') AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'TRAINER\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'TRAINER\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_trainer_update"',
      'CREATE TRIGGER "sync_trainer_update" AFTER UPDATE ON "User" WHEN (OLD."role" = \'COACH\' OR NEW."role" = \'COACH\') AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'TRAINER\', NEW."id", CASE WHEN NEW."role" != \'COACH\' THEN \'ARCHIVE\' ELSE \'UPSERT\' END, lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'TRAINER\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_group_insert"',
      'CREATE TRIGGER "sync_group_insert" AFTER INSERT ON "DanceGroup" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'GROUP\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'GROUP\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_group_update"',
      'CREATE TRIGGER "sync_group_update" AFTER UPDATE ON "DanceGroup" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'GROUP\', NEW."id", CASE WHEN NEW."archivedAt" IS NOT NULL OR NEW."status" = \'ARCHIVED\' THEN \'ARCHIVE\' ELSE \'UPSERT\' END, lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'GROUP\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_student_insert"',
      'CREATE TRIGGER "sync_student_insert" AFTER INSERT ON "Student" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'STUDENT_IDENTITY\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'STUDENT_IDENTITY\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_student_update"',
      'CREATE TRIGGER "sync_student_update" AFTER UPDATE ON "Student" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'STUDENT_IDENTITY\', NEW."id", CASE WHEN NEW."archivedAt" IS NOT NULL OR NEW."status" = \'ARCHIVED\' THEN \'ARCHIVE\' ELSE \'UPSERT\' END, lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'STUDENT_IDENTITY\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_student_contact_insert"',
      'CREATE TRIGGER "sync_student_contact_insert" AFTER INSERT ON "StudentContact" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'STUDENT_CONTACT\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'STUDENT_CONTACT\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_student_contact_update"',
      'CREATE TRIGGER "sync_student_contact_update" AFTER UPDATE ON "StudentContact" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'STUDENT_CONTACT\', NEW."id", CASE WHEN NEW."archivedAt" IS NOT NULL THEN \'ARCHIVE\' ELSE \'UPSERT\' END, lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'STUDENT_CONTACT\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_enrollment_insert"',
      'CREATE TRIGGER "sync_enrollment_insert" AFTER INSERT ON "Enrollment" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'GROUP_MEMBERSHIP\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'GROUP_MEMBERSHIP\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_enrollment_update"',
      'CREATE TRIGGER "sync_enrollment_update" AFTER UPDATE ON "Enrollment" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'GROUP_MEMBERSHIP\', NEW."id", CASE WHEN NEW."status" = \'LEFT\' OR NEW."leftAt" IS NOT NULL THEN \'ARCHIVE\' ELSE \'UPSERT\' END, lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'GROUP_MEMBERSHIP\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_schedule_insert"',
      'CREATE TRIGGER "sync_schedule_insert" AFTER INSERT ON "WeeklySchedule" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'SCHEDULE\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'SCHEDULE\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_schedule_update"',
      'CREATE TRIGGER "sync_schedule_update" AFTER UPDATE ON "WeeklySchedule" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'SCHEDULE\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'SCHEDULE\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_lesson_insert"',
      'CREATE TRIGGER "sync_lesson_insert" AFTER INSERT ON "Lesson" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'LESSON\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'LESSON\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_lesson_update"',
      'CREATE TRIGGER "sync_lesson_update" AFTER UPDATE ON "Lesson" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'LESSON\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'LESSON\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_substitution_insert"',
      'CREATE TRIGGER "sync_substitution_insert" AFTER INSERT ON "TrainerSubstitution" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'SUBSTITUTION\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'SUBSTITUTION\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_card_insert"',
      'CREATE TRIGGER "sync_card_insert" AFTER INSERT ON "MembershipCard" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'CARD\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'CARD\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_card_update"',
      'CREATE TRIGGER "sync_card_update" AFTER UPDATE ON "MembershipCard" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'CARD\', NEW."id", CASE WHEN NEW."status" = \'ARCHIVED\' OR NEW."archivedAt" IS NOT NULL THEN \'ARCHIVE\' ELSE \'UPSERT\' END, lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'CARD\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_tariff_insert"',
      'CREATE TRIGGER "sync_tariff_insert" AFTER INSERT ON "Tariff" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'TARIFF\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'TARIFF\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_tariff_update"',
      'CREATE TRIGGER "sync_tariff_update" AFTER UPDATE ON "Tariff" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'TARIFF\', NEW."id", CASE WHEN NEW."archivedAt" IS NOT NULL THEN \'ARCHIVE\' ELSE \'UPSERT\' END, lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'TARIFF\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_subscription_insert"',
      'CREATE TRIGGER "sync_subscription_insert" AFTER INSERT ON "Subscription" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'SUBSCRIPTION\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'SUBSCRIPTION\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_subscription_update"',
      'CREATE TRIGGER "sync_subscription_update" AFTER UPDATE ON "Subscription" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'SUBSCRIPTION\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'SUBSCRIPTION\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_ledger_insert"',
      'CREATE TRIGGER "sync_ledger_insert" AFTER INSERT ON "SubscriptionLedger" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'SUBSCRIPTION_LEDGER\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'SUBSCRIPTION_LEDGER\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_attendance_insert"',
      'CREATE TRIGGER "sync_attendance_insert" AFTER INSERT ON "Attendance" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'ATTENDANCE\', NEW."lessonId" || \':\' || NEW."studentId", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'ATTENDANCE\' AND "entityId"=(NEW."lessonId" || \':\' || NEW."studentId")),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_attendance_update"',
      'CREATE TRIGGER "sync_attendance_update" AFTER UPDATE ON "Attendance" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'ATTENDANCE\', NEW."lessonId" || \':\' || NEW."studentId", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'ATTENDANCE\' AND "entityId"=(NEW."lessonId" || \':\' || NEW."studentId")),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_student_note_insert"',
      'CREATE TRIGGER "sync_student_note_insert" AFTER INSERT ON "StudentNote" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'STUDENT_NOTE\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'STUDENT_NOTE\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
      'DROP TRIGGER IF EXISTS "sync_student_note_update"',
      'CREATE TRIGGER "sync_student_note_update" AFTER UPDATE ON "StudentNote" WHEN (1=1) AND COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'STUDENT_NOTE\', NEW."id", CASE WHEN NEW."archivedAt" IS NOT NULL THEN \'ARCHIVE\' ELSE \'UPSERT\' END, lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'STUDENT_NOTE\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\nEND',
    ],
  },
  {
    id: '20260822000000_trainer_sync_1',
    statements: [
      'ALTER TABLE "User" ADD COLUMN "trainerDescription" TEXT',
      'DROP TRIGGER IF EXISTS "sync_group_insert"',
      'CREATE TRIGGER "sync_group_insert" AFTER INSERT ON "DanceGroup" WHEN COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'GROUP\', NEW."id", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'GROUP\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  SELECT lower(hex(randomblob(16))), \'TRAINER\', NEW."coachId", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'TRAINER\' AND "entityId"=NEW."coachId"),0), CURRENT_TIMESTAMP\n  WHERE NEW."coachId" IS NOT NULL;\nEND',
      'DROP TRIGGER IF EXISTS "sync_group_update"',
      'CREATE TRIGGER "sync_group_update" AFTER UPDATE ON "DanceGroup" WHEN COALESCE((SELECT "value" FROM "AppSetting" WHERE "key" = \'integration.applyingRemote\'), \'false\') != \'true\' BEGIN\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  VALUES (lower(hex(randomblob(16))), \'GROUP\', NEW."id", CASE WHEN NEW."archivedAt" IS NOT NULL OR NEW."status" = \'ARCHIVED\' THEN \'ARCHIVE\' ELSE \'UPSERT\' END, lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'GROUP\' AND "entityId"=NEW."id"),0), CURRENT_TIMESTAMP);\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  SELECT lower(hex(randomblob(16))), \'TRAINER\', OLD."coachId", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'TRAINER\' AND "entityId"=OLD."coachId"),0), CURRENT_TIMESTAMP\n  WHERE OLD."coachId" IS NOT NULL\n    AND (OLD."coachId" IS NOT NEW."coachId" OR OLD."direction" IS NOT NEW."direction" OR OLD."archivedAt" IS NOT NEW."archivedAt" OR OLD."status" IS NOT NEW."status");\n  INSERT INTO "SyncOutbox" ("id","entityType","entityId","operation","idempotencyKey","baseRevision","updatedAt")\n  SELECT lower(hex(randomblob(16))), \'TRAINER\', NEW."coachId", \'UPSERT\', lower(hex(randomblob(16))), COALESCE((SELECT "revision" FROM "SyncEntityState" WHERE "entityType"=\'TRAINER\' AND "entityId"=NEW."coachId"),0), CURRENT_TIMESTAMP\n  WHERE NEW."coachId" IS NOT NULL\n    AND NEW."coachId" IS NOT OLD."coachId";\nEND',
    ],
  },
  {
    id: '20260822010000_web_freeze_actions',
    statements: [
      'CREATE TABLE "WebAction" (\n  "id" TEXT NOT NULL PRIMARY KEY,\n  "externalActionId" TEXT NOT NULL,\n  "actionType" TEXT NOT NULL,\n  "crmStudentId" TEXT,\n  "crmSubscriptionId" TEXT,\n  "reason" TEXT,\n  "status" TEXT NOT NULL DEFAULT \'PENDING\',\n  "receivedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  "claimedAt" DATETIME,\n  "processedAt" DATETIME,\n  "processedByUserId" TEXT,\n  "safeResultJson" TEXT,\n  "safeError" TEXT,\n  "completionAttemptCount" INTEGER NOT NULL DEFAULT 0,\n  "nextCompletionAttemptAt" DATETIME,\n  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  "updatedAt" DATETIME NOT NULL\n)',
      'CREATE UNIQUE INDEX "WebAction_externalActionId_key" ON "WebAction"("externalActionId")',
      'CREATE INDEX "WebAction_status_receivedAt_idx" ON "WebAction"("status", "receivedAt")',
      'CREATE INDEX "WebAction_crmStudentId_idx" ON "WebAction"("crmStudentId")',
      'CREATE INDEX "WebAction_crmSubscriptionId_idx" ON "WebAction"("crmSubscriptionId")',
      'CREATE INDEX "WebAction_nextCompletionAttemptAt_idx" ON "WebAction"("nextCompletionAttemptAt")',
    ],
  },
  {
    id: '20260822020000_trainer_attendance_web_actions',
    statements: [
      'ALTER TABLE "WebAction" ADD COLUMN "crmTrainerId" TEXT',
      'ALTER TABLE "WebAction" ADD COLUMN "crmLessonId" TEXT',
      'ALTER TABLE "WebAction" ADD COLUMN "payloadJson" TEXT',
      'CREATE INDEX "WebAction_crmTrainerId_idx" ON "WebAction"("crmTrainerId")',
      'CREATE INDEX "WebAction_crmLessonId_idx" ON "WebAction"("crmLessonId")',
    ],
  },
];
