import type { SyncEntityType } from './integration-service';

type CanonicalSyncOperation = 'UPSERT' | 'ARCHIVE';

export const SYNC_UPSERT_PAYLOAD_FIELDS = {
  ATTENDANCE: [
    'id',
    'lessonId',
    'studentId',
    'status',
    'markedAt',
    'comment',
    'directPaymentId',
    'directPaymentOperationId',
    'directPaymentTariffId',
  ],
  BRANCH: ['id', 'name', 'address', 'phone', 'description', 'isActive', 'archivedAt', 'updatedAt'],
  CARD: [
    'id',
    'barcode',
    'studentId',
    'status',
    'issuedAt',
    'unassignedAt',
    'blockedAt',
    'archivedAt',
    'notes',
    'updatedAt',
  ],
  GROUP: [
    'id',
    'name',
    'direction',
    'ageFrom',
    'ageTo',
    'assistantCoachId',
    'branchId',
    'coachId',
    'color',
    'capacity',
    'description',
    'archivedAt',
    'status',
    'updatedAt',
  ],
  GROUP_MEMBERSHIP: [
    'id',
    'studentId',
    'groupId',
    'active',
    'status',
    'joinedAt',
    'leftAt',
    'notes',
    'updatedAt',
  ],
  LESSON: [
    'id',
    'branchId',
    'coachId',
    'endsAt',
    'groupId',
    'roomId',
    'room',
    'scheduleTemplateId',
    'startsAt',
    'status',
    'cancellationReason',
    'notes',
    'attendanceCompletedAt',
    'makeupForLessonId',
    'makeupRequired',
    'originalEndsAt',
    'originalStartsAt',
    'payoutCategory',
    'rescheduledAt',
    'rescheduledFromCoachId',
    'rescheduledFromRoomId',
    'updatedAt',
  ],
  PUBLICATION: [
    'id',
    'type',
    'title',
    'body',
    'status',
    'audienceMode',
    'targets',
    'mediaRef',
    'publishAt',
    'expiresAt',
    'eventStartsAt',
    'eventLocation',
    'author',
    'updatedAt',
  ],
  ROOM: [
    'id',
    'branchId',
    'name',
    'capacity',
    'description',
    'floor',
    'areaSquareMeters',
    'colorKey',
    'isActive',
    'archivedAt',
    'sortOrder',
    'updatedAt',
  ],
  SCHEDULE: [
    'id',
    'branchId',
    'coachId',
    'endTime',
    'groupId',
    'isActive',
    'roomId',
    'room',
    'startTime',
    'updatedAt',
    'validFrom',
    'validTo',
    'weekday',
  ],
  STUDENT_CONTACT: [
    'id',
    'studentId',
    'fullName',
    'relationship',
    'phone',
    'secondaryPhone',
    'email',
    'telegram',
    'whatsapp',
    'isPrimary',
    'notes',
    'archivedAt',
    'updatedAt',
  ],
  STUDENT_IDENTITY: [
    'id',
    'firstName',
    'lastName',
    'middleName',
    'birthDate',
    'gender',
    'phone',
    'email',
    'branchId',
    'status',
    'activeGroupIds',
    'notes',
    'archivedAt',
    'updatedAt',
  ],
  STUDENT_NOTE: ['id', 'studentId', 'authorName', 'text', 'createdAt', 'updatedAt', 'archivedAt'],
  SUBSCRIPTION: [
    'id',
    'studentId',
    'tariffId',
    'branchId',
    'purchasedAt',
    'startsAt',
    'expiresAt',
    'lessonLimit',
    'lessonsUsed',
    'status',
    'freezeStartedAt',
    'freezeEndsAt',
    'frozenDaysUsed',
    'salePrice',
    'notes',
    'sequenceAfterSubscriptionId',
    'updatedAt',
  ],
  SUBSCRIPTION_LEDGER: [
    'id',
    'subscriptionId',
    'studentId',
    'lessonId',
    'attendanceId',
    'type',
    'lessonDelta',
    'amountDelta',
    'comment',
    'reversesLedgerId',
    'periodStartsAt',
    'periodEndsAt',
    'createdAt',
  ],
  SUBSTITUTION: [
    'id',
    'lessonId',
    'originalTrainerId',
    'substituteTrainerId',
    'reason',
    'createdAt',
  ],
  TARIFF: [
    'id',
    'name',
    'branchId',
    'type',
    'lessonCount',
    'validityDays',
    'price',
    'currency',
    'freezeDays',
    'isActive',
    'description',
    'archivedAt',
    'updatedAt',
  ],
  TRAINER: [
    'id',
    'displayName',
    'phone',
    'description',
    'isActive',
    'directions',
    'activeGroupIds',
    'branchIds',
    'updatedAt',
  ],
  TRIAL_APPOINTMENT: [
    'id',
    'externalLeadId',
    'studentId',
    'groupId',
    'lessonId',
    'status',
    'outcome',
    'cancelledAt',
    'supersededAt',
    'version',
    'createdAt',
    'updatedAt',
  ],
} as const satisfies Partial<Record<SyncEntityType, readonly string[]>>;

export function materializeSyncMutation(
  entityType: SyncEntityType,
  entityId: string,
  requestedOperation: CanonicalSyncOperation,
  currentPayload: Record<string, unknown>,
): {
  operation: CanonicalSyncOperation;
  payload: Record<string, unknown>;
  unknownFields: string[];
} {
  const operation = currentPayload.missing === true ? 'ARCHIVE' : requestedOperation;
  if (operation === 'ARCHIVE') {
    return { operation, payload: { id: entityId, missing: true }, unknownFields: [] };
  }
  const allowed = SYNC_UPSERT_PAYLOAD_FIELDS[entityType as keyof typeof SYNC_UPSERT_PAYLOAD_FIELDS];
  const unknownFields = Object.keys(currentPayload)
    .filter((field) => !allowed.includes(field as never))
    .sort();
  return { operation, payload: currentPayload, unknownFields };
}
